# Generated by Django 5.0.9 on 2025-09-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_alter_contactocliente_email_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pedido', models.CharField(max_length=20, unique=True)),
                ('cod_orden_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('total_neto_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
