# Generated by Django 5.0.9 on 2025-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_alter_pedido_cod_pedido_alter_pedido_iva_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total_neto_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
