# Generated by Django 5.0.9 on 2025-09-19 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_contactocliente_email_contacto_and_more'),
        ('Pedidos', '0004_alter_pedido_total_neto_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cod_orden_compra',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
