# Generated by Django 5.0.9 on 2025-10-07 23:22

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pedido', models.CharField(blank=True, max_length=20, unique=True)),
                ('cod_orden_compra', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('total_neto_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('iva_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.19'), max_digits=4)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
