# Generated by Django 5.0.9 on 2025-09-03 01:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cod_pedido',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='iva_pedido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.19'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_neto_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
