# Generated by Django 5.0.9 on 2025-09-19 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abonos', '0001_initial'),
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturas.factura'),
        ),
    ]
