# Generated by Django 5.0.9 on 2025-09-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='email_contacto',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono_contacto',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
