# Generated by Django 5.0.9 on 2025-10-07 23:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abono', models.DateField(default=datetime.date.today)),
                ('total_abono', models.DecimalField(decimal_places=2, max_digits=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='Facturas.factura')),
            ],
        ),
    ]
