# Generated by Django 5.0.9 on 2025-09-19 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abono', models.DateField(default=datetime.date.today)),
                ('total_abono', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
