# Generated by Django 5.0.9 on 2025-09-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(blank=True, choices=[('No definido', 'No definido'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50, null=True)),
                ('tamano_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_producto', models.TextField(blank=True, null=True)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('precio_unitario_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido')),
            ],
        ),
    ]
