# Generated by Django 5.0.9 on 2025-09-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_producto',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario_producto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_producto',
            field=models.CharField(blank=True, choices=[('No definido', 'No definido'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
