# Generated by Django 5.0.9 on 2025-09-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_guia_despacho', models.CharField(max_length=20, unique=True)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('observacion_despacho', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField()),
                ('nombre_repartidor', models.CharField(max_length=100)),
                ('guia_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Despachos.guiadespacho')),
            ],
        ),
    ]
