# Generated by Django 5.0.9 on 2025-10-07 23:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_guia_despacho', models.CharField(max_length=20, unique=True)),
                ('fecha_despacho', models.DateField(default=datetime.date.today)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('observacion_despacho', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField()),
                ('nombre_repartidor', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
                ('guia_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Despachos.guiadespacho')),
            ],
        ),
    ]
