# Generated by Django 5.0.9 on 2025-09-19 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Despachos', '0001_initial'),
        ('Pedidos', '0004_alter_pedido_total_neto_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadespacho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedidos.pedido'),
        ),
    ]
