# Generated by Django 5.0.9 on 2025-09-19 04:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_alter_contactocliente_email_contacto_and_more'),
        ('Pedidos', '0004_alter_pedido_total_neto_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision_factura', models.DateField(default=datetime.date.today)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado_factura', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedidos.pedido')),
            ],
        ),
    ]
