# Generated by Django 5.0.9 on 2025-09-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
    ]
